### ISSUE TITLE
Games doesn’t launch

### ISSUE THREAD

**Issue by niklasalkin** [PhilipK/BoilR#62] opened 2022-03-28 15:23 UTC
I’m an absolute beginner with Linux so this is probably obvious but: I got my Steam Deck today. Downloaded and installed Heroic games launcher and downloaded a couple of games from Epic (intend to also use gog). Ran the UI variant of BoilR and it synced (found a spelling error here, the UI says “synched”). Games show up in Steam but doesn’t launch when I hit play. What am I missing?

**Comment by PhilipK** [comment] 2022-03-28 16:20
(Un)fortunatly it is not just you. Multiple people have reported that there is a problem with launching heroic games from the steam deck.
The problem is that I do not have a steam deck, and I have not been able to reproduce it on any other setup (including arch linux which steam os is based on). 
This might be one of those bugs that will persist for steam deck until i get mine (Q2).

**Comment by PhilipK** [comment] 2022-03-28 16:34
If you have time to help, can you post the content of one of the shortcuts that does not work?

Here is an example from my linux install:

name:
while True: learn()

target:
env XDG_CONFIG_HOME=/home/philip/.var/app/com.heroicgameslauncher.hgl/config /var/lib/flatpak/app/com.heroicgameslauncher.hgl/current/active/files/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary

launch options:
launch 4f272a49a39742b795d63e1f483a7c7

**Comment by kuynh** [comment] 2022-03-28 22:39
Perhaps the problem is due to heroic launcher being a flatpak but I will post an example from mine.

Name:
Rocket League

Target:
env XDG_CONFIG_HOME=/home/deck/.var/app/com.heroicgameslauncher.hgl/config /var/lib/flatpak/app/com.heroicgameslauncher.hgl/current/active/files/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary

Launch Options:
launch Sugar

**Comment by PhilipK** [comment] 2022-03-31 05:37
Scratch my previous statement about it not being fixed till I get a deck.
I have a solution on a branch now, just need to clean it up and then I need someone with a deck to confirm it also works for them, but I am fairly certain that it will.

**Comment by kuynh** [comment] 2022-03-31 06:18
Good to hear. I will happily test this new release.

**Comment by PhilipK** [comment] 2022-03-31 06:55
I expect there will be a pre-release version in 12 hours or so, i will tag the people that have reported they have this problem.

**Comment by PhilipK** [comment] 2022-03-31 15:41
@kuynh  and/or @niklasalkin  can you test if this pre-release version works with the steamdeck?
https://github.com/PhilipK/BoilR/releases/tag/v.0.9.21

**Comment by PhilipK** [comment] 2022-03-31 20:23
Others have confirmed that this works on steam deck now (if you select a proton version for the game), so I will close this issue.
If it does not work for you , we can reopen the issue.

**Closed by PhilipK** 2022-03-31 20:23 UTC

**Comment by kuynh** [comment] 2022-03-31 23:04
It seems to be loading the game for a lot longer than the usual instant send back to steamui but it still does not launch. I'm happy to hear that it works for others but now I wonder what's wrong with my device.

**Comment by kuynh** [comment] 2022-04-01 00:20
I've found that it works for my other games but not for rocket league for some reason.

**Comment by PhilipK** [comment] 2022-04-01 03:54
I will reopen this issue:
https://github.com/PhilipK/BoilR/issues/50

Since it seems to be Rocket League specific
