### ISSUE TITLE
[Issue] New shortcuts added are not getting images populated

### ISSUE THREAD

**Issue by drewbaumann** [PhilipK/BoilR#189] opened 2022-07-25 18:18 UTC
When I add a new steam shortcut to Steam (via Lutris - Flatpak) I typically open Boilr and go to  the Images navigation (since Lutris games arent showing up under the default view). I can then typically see all my non steam games with their images populated.

However, recently I have noticed games not downloading the images automatically. So sometimes the title of the game is listed without an image in the list. Or I see the images from the last game I imported set under the new games title. When I click into the game with the incorrect images I cannot seem to change the images. I have tried correcting the title, clicking the images to attempt to replace (they are not set after clicking new ones), and at this point I am out of ideas.

I am happy to debug and share more information as necessary. I am using a Steam Deck with Boilr installed via Flatpak.

**Comment by PhilipK** [comment] 2022-07-27 10:14
Can you try to post some screenshots of what this looks like?
Also, would you try to launch BoilR through a terminal ? And post its debug output?

**Comment by PhilipK** [comment] 2022-09-07 05:03
Can you try to reproduce this in the newest version. 1.4.8?

**Comment by PhilipK** [comment] 2022-09-08 18:21
I am pretty sure this is solved in 1.4.8 since I saw that bug before, but not after 1.4.8. I am going to close this issue. If it is still there, please let me know and I will reopen the issue.

**Closed by PhilipK** 2022-09-08 18:21 UTC
Labels: bug
