### ISSUE TITLE
Can't choose the install location for Origin (EA app) or Uplay (Ubisoft Connect)

### ISSUE THREAD

**Issue by BitGrub** [PhilipK/BoilR#349] opened 2023-06-06 22:47 UTC
**Describe the bug**
Can't import games from EA or Ubisoft, and the settings page is lacking the option to choose the install location of Origin (EA app) and Uplay (Ubisoft Connect)

**Desktop (please complete the following information):**
 - OS: Windows 11 latest public non preview build
 - BoilR Version: v.1.8.0

**Additional context**
Maybe it's looking for the **legacy** apps in their default locations, but it's still odd that I can't pick a location, even for the discontinued launchers
![image](https://github.com/PhilipK/BoilR/assets/20694416/215f97d8-dc90-42d9-a82f-7dd34f7b7ed9)

**Comment by PhilipK** [comment] 2023-06-07 06:14
Thanks for the bug report, i should have time to look at this this weekend

**Comment by PhilipK** [comment] 2023-06-10 09:52
Okay, I looked into it and now I remember why this was removed. On windows BoilR looks at the windows registry to find out where things are installed. So it should not need to have a manual path at all.

Can you try to open boilr from a terminal and share the terminal output (log) to see where the problem is here and figure out why it can't find the games then.

It seems to work on the windows machines I have access to test on.

**Comment by BitGrub** [comment] 2023-06-10 10:19
Hello! Thanks for looking into it, I really appreciate it! Though it's looking like it's some kind of PEBKAC error..

The Ubisoft games I have (which do show up in Ubisoft Connect and can only be run/updated from there) were bought and initially installed from Epic Games. BoilR at least detects these games and attributes them to Epic. 

Similarly, the EA games I have, were initially installed from the Xbox app (because of Game Pass subscription). BoilR does not detect these at all.

I will try downloading some games directly from the Ubistoft/EA apps and report back when they're done.

Could it be that I'm using the new(ish) EA and Ubisoft Connect apps instead of Origin and Uplay?


Thanks again

**Comment by PhilipK** [comment] 2023-06-10 10:28
Yeah I will have to look into if I can get BoilR working with the new ones. Might be why.

Also looking into gamepass games at the moment, maybe that can help with some of them as well.

**Comment by BitGrub** [comment] 2023-06-10 10:50
Okay, so Ubisoft Connect works, games are detected from Epic or UC itself.

EA does not in any capacity. Can close the issue if you want.

**Comment by PhilipK** [comment] 2023-06-10 22:16
Yeah, i will close this as this is more the fact that EA is not working yet, but that is requested here:
https://github.com/PhilipK/BoilR/issues/326

**Closed by PhilipK** 2023-06-10 22:16 UTC
Labels: bug
