### ISSUE TITLE
Doesn't see my Itch library.

### ISSUE THREAD

**Issue by ritzbitz00** [PhilipK/BoilR#192] opened 2022-07-27 07:33 UTC
I'm using windows 10. My itch folder is at the default path, but the games are installed to another drive. Itch shows in the last but not the games. interacting with the itch settings (checking/unchecking, manually adding the path in) make it disappear from the list entirely. I've also tried pointing to the installation location folder with no success.

![image](https://user-images.githubusercontent.com/92691137/181188365-f52cae2e-1fc0-45f9-9e99-27b83c636094.png)

**Comment by PhilipK** [comment] 2022-07-27 10:11
I am not able to reproduce this, even when I have itch games installed to multiple locations. My settings are just left blank 
![image](https://user-images.githubusercontent.com/544652/181222236-eb4399bc-779b-47da-849d-267cb21872a2.png)
I do run Windows 11, but I don't think that it should matter.

**Comment by ritzbitz00** [comment] 2022-07-27 23:38
@PhilipK Can you share the filepath where your itch games are installed? Its possible that since my games are not installed to a default location that it is effecting the results. Itch is installed to the default path, but games are installed to a different drive.

**Comment by PhilipK** [comment] 2022-07-28 08:05
Mine is almost identical to your, expect, I don't have a space in the folder name that is installed to the d drive (it's just called d:\itch), can you try to install to d without the space in the folder name?

**Comment by ritzbitz00** [comment] 2022-07-29 09:11
replacing the space with an underscore and setting the new location in itch made the items appear. Thanks!

**Comment by PhilipK** [comment] 2022-07-31 11:47
The weird thing is, I am still not able to reproduce this, even if i name my folder exactly the same yours. I am going to close this, in hopes that it is a one off, but will reopen it if others have the same problem.

**Closed by PhilipK** 2022-07-31 11:47 UTC
Labels: bug
