### ISSUE TITLE
Unable to write collections

### ISSUE THREAD

**Issue by Squazz** [PhilipK/BoilR#71] opened 2022-04-02 18:01 UTC
v.0.9.24 - windows ui
With Steam (Steam Client Service) stopped / shut down, I'm unable to write collections

![image](https://user-images.githubusercontent.com/1504055/161395425-9118bec2-1779-441d-854a-16a0995d29b3.png)
![image](https://user-images.githubusercontent.com/1504055/161395462-c89eb012-6f19-406a-ba93-6a6490eb30ed.png)

I'm finding it hard what other information I can provide to help figure out what could be the underlying issue

**Comment by GodZilly** [comment] 2022-04-03 09:57
In your screenshot you show that the Steam SERVICE is stopped, but have you checked in Task manager that the Steam client isn't running?

**Comment by Squazz** [comment] 2022-04-03 10:26
Yes, its not running there either :)

**Comment by Squazz** [comment] 2022-04-11 07:09
I can confirm that this is still an issue in v.1.0.3

**Comment by PhilipK** [comment] 2022-04-13 08:42
I have heard from other sources that they also has this problem, so it is not just you. I just can't reproduce it myself currently.

**Comment by cherokee93** [comment] 2022-05-01 16:31
![image](https://user-images.githubusercontent.com/12370126/166155277-61dad765-5dbc-4a4b-91ef-60a7ff26f5cc.png)
Same here with my steam deck, I'll restart and try again

**Comment by NightHammer1000** [comment] 2022-05-12 19:35
Can confirm this myself. No Collections created here too. In both Native and Flatpak

**Comment by hgouveia** [comment] 2022-05-13 18:37
i have the same issue, my steam is installed in a different drive and folder, and it seems is ignoring the steam path from the settings and using instead hardcode path like $HOME (*linux) and "Program Files (x86)", it should use the path from the `config.toml` 

https://github.com/PhilipK/BoilR/blob/main/src/steam/collections.rs#L173-L210

**Comment by PhilipK** [comment] 2022-08-03 18:40
Alright, this seems to be fixed in the newest version https://github.com/PhilipK/BoilR/releases/tag/v.1.4.3 
I have testet on a windows, linux and steamdeck setup, it works on all of them for me now.
Can someone confirm that it works for them as well?

The problem seems to have been the rusty-leveldb package/crate that was used to write to steams leveldb, after i updated the package to the newest version things started working.

If someone can confirm it works for them I will close this issue.

**Comment by Squazz** [comment] 2022-08-03 19:40
Yesterday I used version 1.4.1, there it didn't (always) work, it did some times.
But I can confirm that it worked just now when I tried on 1.4.3.

I haven't battletested it multiple times, but on my first try, it seems to work :)

**Comment by PhilipK** [comment] 2022-08-04 06:31
Alright I am going to close this then.
If anyone experiences that it still does not work post comment here and I will reopen the issue

**Closed by PhilipK** 2022-08-04 06:31 UTC
Labels: bug

**Comment by lublak** [comment] 2022-08-04 08:21
@PhilipK it works fine :) thanks.

**Comment by ZoidbergForPresident** [comment] 2023-05-15 08:23
Hi! It seems I'm having this issue right now. But the field where I should have the steam folder is empty, maybe it's related? The new shortcuts are created though just not put in the existing collections... Steamdeck here btw.

**Comment by PhilipK** [comment] 2023-05-15 17:18
@ZoidbergForPresident does everything else work? Just the collections missing?

**Comment by ZoidbergForPresident** [comment] 2023-05-15 18:08
@PhilipK It would seem so, I redid everything after deleting the collections and I had to readd each game to their new collections.

**Comment by PhilipK** [comment] 2023-05-16 07:12
@ZoidbergForPresident I will have to play around with it to see if I can reproduce it.
