### ISSUE TITLE
is there a way to get boilr to scan other drives than just c: drive ?

### ISSUE THREAD

**Issue by Orignaldorito** [PhilipK/BoilR#202] opened 2022-08-12 12:25 UTC
i cant seem to find any setting to get boilr to scan any drives other than the c drive

**Comment by PhilipK** [comment] 2022-08-12 13:41
Can you try to specify a bit more what you are experiencing? BoilR does not
scan the c drive, as an example it works on Linux which does not have the
concept of a c drive

**Comment by Orignaldorito** [comment] 2022-08-12 13:52
I'm using the windows_boilR.exe on a windows pc. when i launch it i can see it has detected a few games, these are the games that are installed on the c: drive of my windows pc. i have loads of other games and launchers installed on others drives such as e: and f: none of these games or launchers that are installed on these drives are detected by the windows_BoilR.exe application. When BoilR is detecting games i can see from the console like window boilR opens up that it is only searching the C: drive and does not make an attempt to search other drives such as e: and f:. I have checked the settings of BoilR and there is no option for me to manually select drives or locations to detect some of my launchers and games that are installed on drives other than the c: drive

**Comment by PhilipK** [comment] 2022-08-12 16:02
BoilR doesn' scan a drive.
Depending on the launcher it does a bunch of other stuff to find the games.
Can you mention which launchers are missing and which games are missing.
Also have you tried to change the settings? Normally if you leave the settings be on windows it can pick up things.
I personally have multiple drives on my windows installation.

**Comment by PhilipK** [comment] 2022-09-07 17:40
I am going to close this, I cannot reproduce the error (even when installing to another drive). On windows BoilR uses the windows registry to find most launchers, so it should not matter which drive is used. If someone can explain the this bug to me I can reopen it.

**Closed by PhilipK** 2022-09-07 17:40 UTC
Labels: bug
