### ISSUE TITLE
Synchronizing hangs

### ISSUE THREAD

**Issue by Sadasad1** [PhilipK/BoilR#33] opened 2022-03-12 16:00 UTC
After clicking synchronize it's stuck on searching for game images. It picks already existing non Steam games on Steam (all of them are in log) and then it hangs.

![Console](https://user-images.githubusercontent.com/73360960/158024812-33b6c80c-6617-462e-951d-08a8e82597b7.png)

**Comment by fschaupp** [comment] 2022-03-12 16:53
As far as I could debug it, it never returns a result form the line
`36| let search = self.client.search(query.as_ref()).await?;` in src/steamgriddb/cached_search.rs
Maybe @PhilipK  could have a look. It seems to me like a problem in the steamgriddb library at a first peek.

**Comment by PhilipK** [comment] 2022-03-13 11:33
I am wondering if that TM in the batman name might have something to do with this. I will try to reproduce this by adding some custom shortcuts with lots of random non-url-safe characters in them.

**Comment by jrtberlin** [comment] 2022-03-13 13:54
I get the same issue, but I only have games with `-`,`:`,`.`,`_` and spaces in them. 
When I disable the "Download Images" option, it works.

**Comment by PhilipK** [comment] 2022-03-13 14:47
Alright, new theory, this might be related to how BoilR downloads multiple images in parallel, maybe the synchronization on it fails. Hard to debug when I can't reproduce it.

Would it be possible for someone to upload a shortcut file that makes it fail?

**Comment by jrtberlin** [comment] 2022-03-13 14:49
> Would it be possible for someone to upload a shortcut file that makes it fail?

Where is it located?

**Comment by PhilipK** [comment] 2022-03-13 14:58
Alternatively, maybe a configuration option that makes it download images one by one.

**Comment by PhilipK** [comment] 2022-03-13 15:01
> > Would it be possible for someone to upload a shortcut file that makes it fail?
> 
> Where is it located?

On windows:
C:\Program Files (x86)\Steam\userdata\xxxxx\config\shortcuts.vdf

On deck/linux i believe it is:
/home/deck/.steam/steam/userdata/xxxxx/config/shortcuts.vdf

Where xxxxx is your user number

**Comment by Sadasad1** [comment] 2022-03-13 16:04
[shortcuts.zip](https://github.com/PhilipK/BoilR/files/8240009/shortcuts.zip)

**Comment by PhilipK** [comment] 2022-03-13 17:22
Alright, using your shortcuts @Sadasad1 i was able to reproduce the error. There is a workaround for now, and that is to run the cli instead of the ui. It seems that the UI version hangs on your games, but the cli just works. So, a workaround could be to open the UI for the initla setup, configure what you want, click the "save settings" and then run the CLI from there instead.

I will try to find out why the ui version hangs while the cli does not.

**Comment by PhilipK** [comment] 2022-03-13 21:24
Found the bug, it was a threading issue with Tokio and fltk, long story short, it will be fixed in the next release.

**Comment by PhilipK** [comment] 2022-03-13 21:42
There is a new release, can someone confirm that it also works for them?
https://github.com/PhilipK/BoilR/releases/tag/v.0.9.8

**Comment by jrtberlin** [comment] 2022-03-13 21:44
I can confirm that 0.9.8 works.

**Closed** 2022-03-13 22:03 UTC
