### ISSUE TITLE
Package as Flatpak and publish on Flathub

### ISSUE THREAD

**Issue by jrtberlin** [PhilipK/BoilR#38] opened 2022-03-13 15:00 UTC
Since the Steam Deck comes with Flathub enabled and Discover pre-installed, It would be really nice to have the GUI build of BoilR available on Flathub.

**Comment by PhilipK** [comment] 2022-03-13 15:35
Agreed, it should be fairly simple since BoilR has no dependencies, so flat packs are not really needed. But, I agree, it would be nice to have it easily installable from the hub.

**Comment by PhilipK** [comment] 2022-04-18 12:18
@casept and @jrtberlin I see that you have forks that has started the work on flatpak, is there anything I can do to help?
I am thinking that the biggest problem is that BoilR needs access to a lot of different pahts in the file system?

**Comment by casept** [comment] 2022-04-18 15:02
I've gotten the application to run, but it doesn't yet automatically detect flatpaked Heroic's install directory. I haven't looked at boilr's code yet, but I suspect that this is indeed a path-related issue.

Also, there's an issue related to dependency management which prevent publication to Flathub in the current state. Because Flathub prohibits network access during builds for reproducibility reasons, the `Cargo.lock` file has to be converted to a format `flatpak-builder` understands as it has to pull dependencies instead of cargo. This can be done by including https://github.com/flatpak/flatpak-builder-tools/tree/master/cargo as a submodule and running it before the build. However, Flathub doesn't permit running code before builds. We'd therefore have to come up with some solution to run the script and check the output into the repo automatically so the two lockfiles don't drift. Perhaps a pre-commit hook could help here?

**Comment by PhilipK** [comment] 2022-04-18 16:16
I guess we can setup a github action that checks if there is a change to the lockfile and then runs the tool to generate the flatpak file and commits it.
Would that be an option?

**Comment by PhilipK** [comment] 2022-04-28 11:40
@casept An idea. Since the process of making a release is currently a manual step (and I kind of like that).
Would it be possible to make an initial flatpak version that does not solve the problem of setting up flatpak-builder automatically, but maybe just have a script that is called that ensures that things are set up correctly for the build?
Then we can solve the problem of automating the flatpak-builder file later, or when the release process is an automatic step?

**Comment by PhilipK** [comment] 2022-04-28 19:48
@casept sorry to spam you, but I checked out your code from your fork, really good job!  I added it to a branch, i then tinkered around a bit and i got BoilR to run through the flatpak build. With a few changes it can pick up itch and heroic games. 

https://github.com/PhilipK/BoilR/tree/casept_flatpak

**Comment by PhilipK** [comment] 2022-04-29 12:52
@casept now that you say it, the same thing happened to me, I thought it was because i had rebuild between each run, but for sure, it must because boilr tries to write to its "local" folder. 
There are a couple things that it tries to write:
* config.toml - settings file that includes stuff like the auth key
* .thumbails - temporary thumbnails for when the user manually select an image
* .cache - cache of appid -> steamgriddb id, so it does no have to search for it every import run.

**Comment by casept** [comment] 2022-04-29 13:23
What is the "local" folder? The location where the binary is installed?

**Comment by PhilipK** [comment] 2022-04-29 14:43
Yes, just the binary folder / working dir. "./"

**Comment by PhilipK** [comment] 2022-04-29 14:45
But if we just check for the XDG_CONFIG_DIR environment variable and prepend that to those configuration folders/files inside the rust code then it should be fine?

**Comment by PhilipK** [comment] 2022-05-01 05:43
@casept & @jrtberlin 
I have made this pull request now

https://github.com/PhilipK/BoilR/pull/112
(number 112, which is funny when you are from the EU)

Let me know if you think it looks good.
I have tested it on a couple systems and it seems to work now that I fixed the configuration folder thing

**Comment by casept** [comment] 2022-05-01 17:28
Also works for me on the steam deck, I think it can be merged :+1:

**Comment by PhilipK** [comment] 2022-05-01 17:37
Merged.
Now to make a PR on flathub (well... After the kids are sleeping anyways). 

I will post it here when it is done.

**Comment by PhilipK** [comment] 2022-05-05 17:45
Finally got some time to look at this:

https://github.com/flathub/flathub/pull/3104

**Comment by PhilipK** [comment] 2022-05-06 08:26
Good news everybody

https://github.com/flathub/io.github.philipk.boilr

**Comment by PhilipK** [comment] 2022-05-06 11:51
Again, I don't have a steamdeck, so I would appreciate if someone could test it out :-)

**Comment by PhilipK** [comment] 2022-05-06 16:47
Here is the link to flathub:
https://flathub.org/apps/details/io.github.philipk.boilr

**Comment by PhilipK** [comment] 2022-05-07 04:51
I am going to close this. If anyone find bugs with flathub, then please create them as new issues.

**Closed by PhilipK** 2022-05-07 04:51 UTC
Labels: enhancement
