### ISSUE TITLE
Icon images don't apply in Steam

### ISSUE THREAD

**Issue by Wibbbs** [PhilipK/BoilR#239] opened 2022-09-29 14:07 UTC
**Describe the bug**
Icon images dont seem to apply. 

**To Reproduce**
1. Select an Icon from the icon images for a game
2. Go to steam and the icon is not set for the game. In desktop mode you can see there is no icon. In gaming mode you can see there is no icon set when you bring up the steam menu while in game.

**Expected behavior**
Expect the icon image to be set.

**Screenshots**
I will try to add some screenshots shortly below

**Desktop (please complete the following information):**
 - OS: SteamOS
 - BoilR Version: 1.5.1
 - Launcher: Launcher doesn't seem to matter, I have the same issue with games added from Heroic and game I have added manually.

**Comment by roguesaloon** [comment] 2022-10-02 16:30
I've noticed this issue too, it's probably the biggest issue with BoilR that I have. Steam Rom Manager manages to do this just fine and the icons do seem to be copied over to the directory, so I'm guessing there's just a small bug in the code with merging the vdf. I would look into it further myself but I'm really not very familiar with Rust.

**Comment by PhilipK** [comment] 2022-10-03 19:43
Can you try the newest pre-release?

https://github.com/PhilipK/BoilR/releases/tag/v.1.6.1

I reproduced the error, but running sync with the newest version fixed it.

**Comment by Goldenfreddy0703** [comment] 2022-10-03 19:48
Oh hey, I can try but I'm using steam deck, is there a beta release on the discover store I can test?

**Comment by PhilipK** [comment] 2022-10-03 20:33
@Goldenfreddy0703 the linux version works just fine on steamdeck, just download, rightclick, make it executable, and then run it like on windows.

**Comment by Goldenfreddy0703** [comment] 2022-10-03 20:34
Oh ok thank you

**Comment by roguesaloon** [comment] 2022-10-04 22:28
I'm definitely still seeing this using the latest pre-release v1.6.1 on my steam deck. No icon is present when selecting one and importing a game. Again, the file is copied to `steam/userdata/[id]/config/grid` and a less than ideal work around is to assign the icon (in the steam grid folder) manually in steam after the import.

**Comment by PhilipK** [comment] 2022-10-05 11:42
@roguesaloon even if you do a full import? I saw that it was possible to get in a state, where there where two games added, with the same appid, and boilr would then set the shortcut on one but not the other. I made it so BoilR cleans up on an import so there are no duplicates.

**Comment by roguesaloon** [comment] 2022-10-05 22:04
My specific use case was more for quickly adding art to an already existing steam shortcut (added outside of BoilR), there's no duplicate shortcut, it updates everything correctly except the icon.

**Comment by Wibbbs** [comment] 2022-10-06 03:09
> My specific use case was more for quickly adding art to an already existing steam shortcut (added outside of BoilR), there's no duplicate shortcut, it updates everything correctly except the icon.

Same here. The issue seems to occur only on shortcuts that I added to steam manually, then use boiler to set the art work. Shortcuts actually created by Boilr seem to be ok.

**Comment by PhilipK** [comment] 2022-10-06 04:09
I think I know what the problem is.
Icons are different in steam, than all the other pictures. They must be
referred to directly from from the actual shortcut file. The other images
are indirectly referred to by thier name instead.

BoilR does not touch other shortcuts at all, it only touches Boilr created
shortcuts. This is just a safety thing, I don't want to accidentally delete
or destroy a shortcut that BoilR didn't make.

Since it doesn't touch them it also does not correct the icon field in
those shortcuts.
It downloads the icon image, but does not change the shortcut to use it.

I guess this is fixable by having a toggle in the settings that allows this
modification, defaulted to true. Worst case boilr backs up shortcut files
before it modifies them.

**Comment by PhilipK** [comment] 2022-10-06 20:06
Can someone try this version?
https://github.com/PhilipK/BoilR/releases/tag/v.1.6.2

I was able to reproduce the bug with 1.6.1, but for me 1.6.2 fixed that issue.

**Comment by Pixxel123** [comment] 2022-10-06 21:40
> Can someone try this version? [`v.1.6.2` (release)](https://github.com/PhilipK/BoilR/releases/tag/v.1.6.2)
> 
> I was able to reproduce the bug with 1.6.1, but for me 1.6.2 fixed that issue.

Unfortunately this hasn't fixed it for me, using non-Steam Spider-Man Remastered still has no icons even though one is set. Missing icon shown in the top left corner in this screenshot.

![image](https://user-images.githubusercontent.com/36304206/194423585-e0e829f7-efe4-485c-8ec9-f4a85d48b3d4.png)

**Comment by PhilipK** [comment] 2022-10-07 03:49
Icons are extra "picky about showing up" have you tried restarting the
deck?

**Comment by Pixxel123** [comment] 2022-10-07 09:13
Sadly a restart didn't fix this, neither Restart, nor Shutdown and power up again...

**Comment by sekuza009** [comment] 2022-10-08 04:35
Same here, adding everything else to the Steam Deck works but the icons still don't go through even on the pre release version.

**Comment by Goldenfreddy0703** [comment] 2022-10-08 14:15
Same here as well

**Comment by PhilipK** [comment] 2022-10-12 17:05
Thanks for reporting the version number problem, it was me who forgot to
update it.
I will have to update the CD pipeline to do it in the future.

**Comment by PhilipK** [comment] 2022-10-12 17:35
Finally able to reproduce this problem on one of my own systems. Don't know what it is yet, but it helps that I can reproduce it.

**Comment by PhilipK** [comment] 2022-10-12 19:54
Alright:
https://github.com/PhilipK/BoilR/releases/tag/v.1.7.1

Here i could reproduce the error with 1.7.0 but not with 1.7.1
Can someone try again?

**Comment by PhilipK** [comment] 2022-10-13 10:31
Great, making it an official release and closing this issue.

**Closed by PhilipK** 2022-10-13 10:31 UTC
Labels: bug

**Comment by sekuza009** [comment] 2022-10-17 17:29
Not sure about everyone else but even with the new release it still doesn't seem to work, the icons are still blank when adding new games.

**Comment by Goldenfreddy0703** [comment] 2022-10-17 19:02
> Not sure about everyone else but even with the new release it still doesn't seem to work, the icons are still blank when adding new games.

It worked for me

**Comment by sekuza009** [comment] 2022-10-17 19:49
Do you have steam open when you try to apply images? Also, were you able to add images to previously added games on Boilr?

**Comment by Goldenfreddy0703** [comment] 2022-10-17 20:18
Yeah but i did have to restart my steam.

**Comment by sekuza009** [comment] 2022-10-23 21:26
> I had this problem also, v1.7.4 , what I do is add the games as non-steam games then go into BoilR and set up the images, icons didn't show up, with steam closed after setting up the images you need to click that icon at the bottom in Import Games tab ( Import your games into steam) and the icons will sync up

Can confirm, that fixed it for me. Thanks a ton!

**Comment by abienz** [comment] 2023-06-12 18:35
Using Boilr v1.8.0 from Flatpak it still doesn't work for me on Desktop using Steam from package manager.
Other images come across fine.

**Comment by weakit** [comment] 2024-07-05 06:25
This is still happening for me with the latest release (v1.9.4) on windows. Can this issue be reopened?
