### ISSUE TITLE
Origin path not working

### ISSUE THREAD

**Issue by Squazz** [PhilipK/BoilR#78] opened 2022-04-11 07:03 UTC
Opening v.1.0.3 in windows UI gives me the following error
![image](https://user-images.githubusercontent.com/1504055/162682503-8a0748e1-b18b-4bf5-9ec8-43aeff5dda61.png)

Navigating to the settings to modify my Origin path, it turns out I'm not able to do that
![image](https://user-images.githubusercontent.com/1504055/162682582-4130f379-11af-4567-a976-f9803986da3c.png)

**Comment by PhilipK** [comment] 2022-04-13 08:13
Reproduced and fixed on windows. Will be in the next release.

**Comment by PhilipK** [comment] 2022-04-13 08:41
I am assuming that this is fixed in the newest release (since i reproduced it) and now it is fixed:
https://github.com/PhilipK/BoilR/releases/tag/v.1.0.4

If it is not fixed for you please comment again and I will reopen the issue.

**Closed by PhilipK** 2022-04-13 08:41 UTC
