### ISSUE TITLE
'No images needed' but no game art in Steam

### ISSUE THREAD

**Issue by arussellsaw** [PhilipK/BoilR#10] opened 2021-10-28 08:59 UTC
hey! thanks for building this, i'm getting 'no images needed' and no images in the steam, is there anything i need to change?
the games definitely exist on steamgriddb (eg snowrunner, hades, & battlefield v)
```C:\Users\alexr\Downloads>windows_BoilR.exe
Found 1 user(s)
Found 5 shortcuts for user: C:\Program Files (x86)\Steam\userdata\{redacted idk if it's sensitive}
Found 4 game(s) for platform EGS
Found 1 game(s) for platform Origin
Saved 5 shortcuts
Finished synchronizing games in: 1.4165ms
Checking for game images
No images needed```

**Comment by PhilipK** [comment] 2022-03-21 21:34
The newest release:
https://github.com/PhilipK/BoilR/releases/tag/v.0.9.15

Has improved image download, and uses the official steam images if it can find it.
Can you see if that helps with you problem?

**Comment by PhilipK** [comment] 2022-03-22 18:55
I am going to close this, since I have not been able to reproduce this bug since version 0.9.15. If you still have problems, please reopen the issue.

**Closed by PhilipK** 2022-03-22 18:55 UTC
