### ISSUE TITLE
Stuck on Wii Games

### ISSUE THREAD

**Issue by bradr3d** [PhilipK/BoilR#29] opened 2022-03-10 22:30 UTC
Hi! Just found this awesome tool. I have a couple of emulated Wii games in my Steam library, and BoilR seems to get stuck on not being able to find images on them (or something, the command line output doesn't tell me what it's doing past "searching"). Am I doing something wrong?

**Comment by bradr3d** [comment] 2022-03-10 22:33
Hrm, the CLI worked perfectly fine.

**Comment by bradr3d** [comment] 2022-03-10 22:39
Okay, now some games seem to have double slashes in their directories, which breaks Steam and doesn't let them open.

**Comment by PhilipK** [comment] 2022-03-11 06:17
Hi, so you are just using it for the art download for games that you have added manually? And then it breaks the shortcuts?

Which OS are you running?
Do you have an example of a before and after path?

**Comment by bradr3d** [comment] 2022-03-11 15:39
I was using BoilR to add Epic, GOG, etc. games. when the UI app was running through my steam games to add art, it was getting stuck on Wii games that I also have in my library, but the tool without a UI breezed through it fine.

I'm running Windows 11.
Here's the path hat it gave on of my Itch games, which doesn't launch: 
![image](https://user-images.githubusercontent.com/17806302/157899218-6d3b4641-23c9-48b9-abec-d3e12597d691.png)

**Comment by PhilipK** [comment] 2022-03-11 19:18
Is that a game from GOG or Epic?

**Comment by bradr3d** [comment] 2022-03-11 22:51
That one is from Itch

**Comment by PhilipK** [comment] 2022-03-14 05:51
The problem with being stuck in the Ui version might actually be another issue that was solved in the newest release, can you try the Ui version again?

**Comment by bradr3d** [comment] 2022-03-17 03:25
i can, but that doesn't explain the itch paths being weird

**Comment by PhilipK** [comment] 2022-03-17 06:57
I know the problem with itch is a separate problem.

**Comment by PhilipK** [comment] 2022-03-18 11:16
The newest release fixes some issues with itch, can you check if that solves your problem? 
https://github.com/PhilipK/BoilR/releases/tag/v.0.9.13

**Comment by PhilipK** [comment] 2022-03-22 18:53
I am going to close this issues since I have not been able to reproduce the bug since 0.9.13. If still have problems, please reopen this issues or create a new one. Thanks for you feedback on the tool!

**Closed by PhilipK** 2022-03-22 18:53 UTC
