### ISSUE TITLE
[Feature Request] Flatpaks (mainly for SteamDeck)

### ISSUE THREAD

**Issue by isopix** [PhilipK/BoilR#57] opened 2022-03-25 20:05 UTC
Hi,

Because SteamDeck's  root filesystem is r/o and get's overwritten every upgrade, its encouraged that everything installed outside of SteamStore be provided as FlatPaks (there's 'Discover' already in 'desktop mode' pinned to taskbar for easy installation)

I don't want Heroic, which is nearly 500MB BloatWare (in comparison to your's 5MB client)

**Comment by PhilipK** [comment] 2022-03-26 05:56
There is already an issue for flatpak support https://github.com/PhilipK/BoilR/issues/38 can we merge the issues or is there something else you request here that is not on the other one?

**Comment by isopix** [comment] 2022-03-26 08:10
It's perfectly fine for me to merge.
Even looks like duplicate, sorry ;-)

**Comment by PhilipK** [comment] 2022-03-27 06:17
Closed because it is a duplicate of
https://github.com/PhilipK/BoilR/issues/38

**Closed by PhilipK** 2022-03-27 06:17 UTC
